begin;

alter table users enable row level security;
alter table deals enable row level security;
alter table deal_payments enable row level security;
alter table collection_attempts enable row level security;
alter table payout_attempts enable row level security;
alter table refund_attempts enable row level security;
alter table dispute_tickets enable row level security;
alter table referrals enable row level security;
alter table bot_settings enable row level security;

revoke all on function claim_deal_payment(bigint, text, numeric, numeric, text, boolean, timestamptz) from public, anon, authenticated;
revoke all on function claim_deal_collection(bigint, text, text) from public, anon, authenticated;
revoke all on function save_prepared_collection(bigint, text, text, timestamptz) from public, anon, authenticated;
revoke all on function mark_collection_submitted(bigint) from public, anon, authenticated;
revoke all on function mark_collection_confirmed(bigint, timestamptz) from public, anon, authenticated;
revoke all on function mark_direct_custody_confirmed(bigint, timestamptz) from public, anon, authenticated;
revoke all on function mark_collection_bounced(bigint, text) from public, anon, authenticated;
revoke all on function mark_collection_failed(bigint, text) from public, anon, authenticated;
revoke all on function request_deal_release(bigint, bigint) from public, anon, authenticated;
revoke all on function claim_deal_buyer(text, bigint) from public, anon, authenticated;
revoke all on function assign_user_referrer(bigint, bigint) from public, anon, authenticated;
revoke all on function credit_referral_reward(bigint, bigint, text, numeric) from public, anon, authenticated;
revoke all on function claim_deal_batch_payout(bigint, text, numeric, text, text, numeric, text)
    from public, anon, authenticated;
revoke all on function save_prepared_payout(bigint, text, text, timestamptz) from public, anon, authenticated;
revoke all on function mark_payout_submitted(bigint) from public, anon, authenticated;
revoke all on function mark_payout_confirmed(bigint) from public, anon, authenticated;
revoke all on function mark_payout_bounced(bigint, text) from public, anon, authenticated;
revoke all on function mark_payout_failed(bigint, text) from public, anon, authenticated;
revoke all on function purge_expired_unsuccessful_deals(integer) from public, anon, authenticated;
revoke all on function assign_deal_wallet_identity() from public, anon, authenticated;
revoke all on function mark_deal_delivered(bigint, bigint, timestamptz) from public, anon, authenticated;
revoke all on function open_deal_dispute(bigint, bigint, text) from public, anon, authenticated;
revoke all on function request_expired_delivery_refund(bigint) from public, anon, authenticated;
revoke all on function request_expired_inspection_release(bigint) from public, anon, authenticated;
revoke all on function activate_refund_after_wallet(bigint) from public, anon, authenticated;
revoke all on function claim_deal_refund(bigint, text, numeric, text, text, text, numeric, text) from public, anon, authenticated;
revoke all on function save_prepared_refund(bigint, text, text, timestamptz) from public, anon, authenticated;
revoke all on function mark_refund_submitted(bigint) from public, anon, authenticated;
revoke all on function mark_refund_confirmed(bigint) from public, anon, authenticated;
revoke all on function mark_refund_bounced(bigint, text) from public, anon, authenticated;
revoke all on function mark_refund_failed(bigint, text) from public, anon, authenticated;
revoke all on function resolve_dispute_release(bigint, text) from public, anon, authenticated;
revoke all on function list_admin_disputes(integer, integer) from public, anon, authenticated;
revoke all on function resolve_dispute_refund(bigint, text) from public, anon, authenticated;

grant execute on function claim_deal_payment(bigint, text, numeric, numeric, text, boolean, timestamptz) to service_role;
grant execute on function claim_deal_collection(bigint, text, text) to service_role;
grant execute on function save_prepared_collection(bigint, text, text, timestamptz) to service_role;
grant execute on function mark_collection_submitted(bigint) to service_role;
grant execute on function mark_collection_confirmed(bigint, timestamptz) to service_role;
grant execute on function mark_direct_custody_confirmed(bigint, timestamptz) to service_role;
grant execute on function mark_collection_bounced(bigint, text) to service_role;
grant execute on function mark_collection_failed(bigint, text) to service_role;
grant execute on function request_deal_release(bigint, bigint) to service_role;
grant execute on function claim_deal_buyer(text, bigint) to service_role;
grant execute on function assign_user_referrer(bigint, bigint) to service_role;
grant execute on function credit_referral_reward(bigint, bigint, text, numeric) to service_role;
grant execute on function claim_deal_batch_payout(bigint, text, numeric, text, text, numeric, text)
    to service_role;
grant execute on function save_prepared_payout(bigint, text, text, timestamptz) to service_role;
grant execute on function mark_payout_submitted(bigint) to service_role;
grant execute on function mark_payout_confirmed(bigint) to service_role;
grant execute on function mark_payout_bounced(bigint, text) to service_role;
grant execute on function mark_payout_failed(bigint, text) to service_role;
grant execute on function purge_expired_unsuccessful_deals(integer) to service_role;
grant usage, select on sequence deal_subwallet_id_seq to service_role;
grant usage, select on sequence deal_wallet_v5_subwallet_seq to service_role;
grant execute on function mark_deal_delivered(bigint, bigint, timestamptz) to service_role;
grant execute on function open_deal_dispute(bigint, bigint, text) to service_role;
grant execute on function request_expired_delivery_refund(bigint) to service_role;
grant execute on function request_expired_inspection_release(bigint) to service_role;
grant execute on function activate_refund_after_wallet(bigint) to service_role;
grant execute on function claim_deal_refund(bigint, text, numeric, text, text, text, numeric, text) to service_role;
grant execute on function save_prepared_refund(bigint, text, text, timestamptz) to service_role;
grant execute on function mark_refund_submitted(bigint) to service_role;
grant execute on function mark_refund_confirmed(bigint) to service_role;
grant execute on function mark_refund_bounced(bigint, text) to service_role;
grant execute on function mark_refund_failed(bigint, text) to service_role;
grant execute on function resolve_dispute_release(bigint, text) to service_role;
grant execute on function list_admin_disputes(integer, integer) to service_role;
grant execute on function resolve_dispute_refund(bigint, text) to service_role;

commit;
