services:
  - type: web
    name: gift-guarant
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    envVars:
      - key: APP_PORT
        value: "10000"
      - key: APP_BASE_URL
        value: https://garant-i3z6.onrender.com
      - key: TELEGRAM_USE_POLLING
        value: "true"
      - key: TELEGRAM_BOT_USERNAME
        value: grntrobot
      - key: SUPPORT_USERNAME
        value: "@not_jammm"
      - key: ADMIN_IDS
        value: "786080766"
      - key: USDT_MASTER_ADDRESS
        value: EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs
      - key: MIN_USDT_DEAL_AMOUNT
        value: "1"
      - key: TON_GUARANT_ADDRESS
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: TON_API_KEY
        sync: false
      - key: TON_MNEMONIC
        sync: false
      - key: SERVICE_FEE_WALLET
        sync: false
