from decimal import Decimal

MIN_PYTHON = (3, 14, 0)
MAX_PYTHON = (3, 14, 3)
TON_DECIMAL_PLACES = Decimal("0.000000001")
USDT_DECIMAL_PLACES = Decimal("0.000001")
USDT_DECIMALS = 6
USDT_MAINNET_MASTER = "EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs"
JETTON_TRANSFER_NOTIFICATION_OPCODE = 0x7362D09C
ADMIN_PAGE_SIZE = 8
BROADCAST_BATCH_SIZE = 500
BROADCAST_DELAY_SECONDS = 0.04
DB_READ_RETRY_ATTEMPTS = 3
DB_INTERACTIVE_READ_RETRY_ATTEMPTS = 1
DB_READ_RETRY_BASE_DELAY_SECONDS = 0.25
DB_MAX_CONCURRENCY = 8
DB_BACKGROUND_MAX_CONCURRENCY = 2
SUPABASE_POSTGREST_TIMEOUT_SECONDS = 8
# Media uploads can briefly exceed ten seconds while Telegram recovers from a
# gateway/network incident.  Polling has its own shorter timeout below, so a
# larger Bot API request timeout does not slow down update fetching or normal
# menu navigation.
TELEGRAM_REQUEST_TIMEOUT_SECONDS = 30
TELEGRAM_POLLING_TIMEOUT_SECONDS = 10
SLOW_DATABASE_WAIT_SECONDS = 0.1
SLOW_DATABASE_REQUEST_SECONDS = 0.5
# Background workers intentionally queue behind their dedicated limiter.
# Warn only when that backpressure becomes abnormally long.
SLOW_BACKGROUND_DATABASE_WAIT_SECONDS = 5.0
SLOW_BACKGROUND_DATABASE_REQUEST_SECONDS = 2.0
# A callback ACK is an external Telegram API round trip. Sub-second latency is
# normal between Render and Telegram; warn only when it becomes user-visible.
SLOW_CALLBACK_ACK_SECONDS = 1.0
SLOW_USER_LOOKUP_SECONDS = 0.5
SLOW_UPDATE_SECONDS = 1.0
EVENT_LOOP_LAG_WARNING_SECONDS = 0.5
EVENT_LOOP_LAG_CONSECUTIVE_SAMPLES = 2
EVENT_LOOP_SEVERE_LAG_WARNING_SECONDS = 2.0
BACKGROUND_WORKER_START_STAGGER_SECONDS = 0.5
TELEGRAM_POLLING_MIN_BACKOFF_SECONDS = 5.0
TELEGRAM_POLLING_MAX_BACKOFF_SECONDS = 30.0
TELEGRAM_POLLING_BACKOFF_FACTOR = 1.5
TELEGRAM_POLLING_BACKOFF_JITTER = 0.1
WALLET_V4_MAX_PAYOUT_MESSAGES = 4
WALLET_V5_MAX_PAYOUT_MESSAGES = 255
WALLET_V5_MAX_SUBWALLET_NUMBER = 0x7FFF
MAX_ERROR_LENGTH = 1_000
PUBLIC_DEAL_ID_BYTES = 5
DEAL_STAGE_TIMEOUT_SECONDS = 60 * 60
CHANNEL_STAGE_TIMEOUT_SECONDS = 24 * 60 * 60
DEAL_PAYMENT_TIMEOUT_SECONDS = DEAL_STAGE_TIMEOUT_SECONDS
SELLER_DELIVERY_TIMEOUT_SECONDS = DEAL_STAGE_TIMEOUT_SECONDS
GIFT_INSPECTION_TIMEOUT_SECONDS = DEAL_STAGE_TIMEOUT_SECONDS
LONG_INSPECTION_TIMEOUT_SECONDS = DEAL_STAGE_TIMEOUT_SECONDS
DISPUTE_DESCRIPTION_MIN_LENGTH = 10
DISPUTE_DESCRIPTION_MAX_LENGTH = 1_000
# Ten percent of the service commission, not ten percent of the deal principal.
REFERRAL_COMMISSION_SHARE = Decimal("0.10")
REFERRAL_MIN_WITHDRAW_TON = Decimal("0.1")
REFERRAL_MIN_WITHDRAW_USDT = Decimal(1)
REFERRAL_WITHDRAW_COMMENT = "Referral Reward"
COMPLETED_DEALS_CHANNEL = "@grnthub"
COMPLETED_DEALS_TOPIC_ID = 4
PUBLIC_BOT_USERNAME = "@grntrobot"
