from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from decimal import Decimal
from typing import Literal, Protocol, TypeAlias, TypedDict, Unpack

from app.core.enums import Currency, DealStatus, Language, TraceStatus
from app.models.dto import CreateDealCommand, PaymentObservation, ReferralStats
from app.models.entities import Deal, PayoutAttempt, User
from app.ton.models import PayoutMessage, PreparedPayout

TelegramId: TypeAlias = int
DealId: TypeAlias = int
AtomicAmount: TypeAlias = int
HealthStatus: TypeAlias = Literal["ok", "starting"]


class ReadinessPayload(TypedDict):
    status: HealthStatus
    checks: dict[str, bool]


class UserChanges(TypedDict, total=False):
    username: str | None
    wallet_address: str | None
    language: Language
    referrer_id: int | None


class UserRepositoryProtocol(Protocol):
    async def ensure_user(
        self,
        telegram_id: TelegramId,
        username: str | None,
        default_language: Language,
    ) -> User: ...

    async def get(self, telegram_id: TelegramId) -> User | None: ...

    async def update(self, telegram_id: TelegramId, **changes: Unpack[UserChanges]) -> User: ...


class DealRepositoryProtocol(Protocol):
    async def create(self, command: CreateDealCommand) -> Deal: ...
    async def activate(self, deal_id: DealId, wallet_address: str) -> Deal: ...
    async def mark_creation_failed(self, deal_id: DealId, reason: str) -> Deal: ...
    async def transition(self, deal_id: DealId, expected: DealStatus, **changes: object) -> Deal: ...
    async def get(self, deal_id: DealId) -> Deal | None: ...
    async def get_by_public_id(self, public_id: str) -> Deal | None: ...
    async def join(self, public_id: str, buyer_id: TelegramId) -> Deal | None: ...
    async def claim_payment(self, deal_id: DealId, payment: PaymentObservation) -> Deal | None: ...
    async def list_for_user(self, telegram_id: TelegramId, page: int, page_size: int) -> tuple[list[Deal], bool]: ...
    async def list_pending(self) -> list[Deal]: ...
    async def expire_unpaid(self, deal_id: DealId) -> Deal: ...
    async def purge_unsuccessful(self, retention_days: int) -> int: ...


class PayoutRepositoryProtocol(Protocol):
    async def claim(self, deal: Deal, destination: str, amount_atomic: int, comment: str) -> PayoutAttempt | None: ...
    async def save_prepared(
        self,
        attempt_id: int,
        external_message_hash: str,
        signed_boc: str,
        valid_until: datetime,
    ) -> PayoutAttempt: ...
    async def mark_submitted(self, attempt_id: int) -> PayoutAttempt: ...
    async def mark_confirmed(self, attempt_id: int) -> Deal | None: ...
    async def mark_bounced(self, attempt_id: int, error: str) -> Deal: ...
    async def mark_failed(self, attempt_id: int, error: str) -> Deal: ...
    async def list_open(self) -> list[PayoutAttempt]: ...


class ReferralRepositoryProtocol(Protocol):
    async def assign_referrer(self, referrer_id: TelegramId, referred_id: TelegramId) -> bool: ...
    async def get_stats(self, referrer_id: TelegramId) -> ReferralStats: ...
    async def add_reward(
        self,
        referrer_id: TelegramId,
        referred_id: TelegramId,
        currency: Currency,
        amount: Decimal,
    ) -> None: ...


class TonGatewayProtocol(Protocol):
    @property
    def is_connected(self) -> bool: ...
    async def start(self) -> None: ...
    async def close(self) -> None: ...
    def normalize_address(self, raw_address: str) -> str: ...
    async def get_deal_address(self, subwallet_id: int) -> str: ...
    async def find_incoming_payment(self, deal: Deal) -> PaymentObservation | None: ...
    async def prepare_batch_payout(self, subwallet_id: int, messages: Sequence[PayoutMessage]) -> PreparedPayout: ...
    async def broadcast(self, signed_boc: str) -> None: ...
    async def get_trace_status(self, normalized_hash: str) -> TraceStatus: ...


class NotificationGatewayProtocol(Protocol):
    async def payment_received(self, deal: Deal, buyer: User | None, seller: User | None) -> None: ...
    async def payout_confirmed(self, deal: Deal, buyer: User | None, seller: User | None) -> None: ...
