from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from decimal import Decimal
from typing import Literal, Protocol, TypeAlias, TypedDict, Unpack

from app.core.enums import Currency, DealStatus, FinancialOperationFlow, Language, TraceStatus
from app.models.dto import CreateDealCommand, DepositScanBatch, PaymentObservation, ReferralCommunity, ReferralProfile, ReferralStats
from app.models.entities import BotSettings, CollectionAttempt, Deal, DepositCursor, DisputeTicket, FinancialOperation, FinancialOperationAttempt, ObservedDeposit, ReferralWithdrawal, UnmatchedPayment, User
from app.ton.models import PayoutMessage, PreparedPayout, TraceResult

TelegramId: TypeAlias = int
DealId: TypeAlias = int
AtomicAmount: TypeAlias = int
HealthStatus: TypeAlias = Literal["ok", "starting"]


class ReadinessPayload(TypedDict):
    status: HealthStatus
    checks: dict[str, bool]


class UserChanges(TypedDict, total=False):
    username: str | None
    wallet_address: str | None
    language: Language
    referrer_id: int | None


class UserRepositoryProtocol(Protocol):
    async def ensure_user(
        self,
        telegram_id: TelegramId,
        username: str | None,
        default_language: Language,
    ) -> User: ...

    async def get(self, telegram_id: TelegramId) -> User | None: ...
    async def get_many(self, telegram_ids: set[TelegramId]) -> dict[TelegramId, User]: ...

    async def update(self, telegram_id: TelegramId, **changes: Unpack[UserChanges]) -> User: ...
    async def list_ids(self, offset: int, limit: int) -> list[int]: ...


class DealRepositoryProtocol(Protocol):
    async def create(self, command: CreateDealCommand) -> Deal: ...
    async def activate(self, deal_id: DealId, wallet_address: str) -> Deal: ...
    async def mark_creation_failed(self, deal_id: DealId, reason: str) -> Deal: ...
    async def transition(self, deal_id: DealId, expected: DealStatus, **changes: object) -> Deal: ...
    async def get(self, deal_id: DealId) -> Deal | None: ...
    async def get_by_public_id(self, public_id: str) -> Deal | None: ...
    async def join(self, public_id: str, buyer_id: TelegramId) -> Deal | None: ...
    async def claim_join_notification(self, deal_id: DealId) -> Deal | None: ...
    async def claim_success_feed_notification(self, deal_id: DealId) -> Deal | None: ...
    async def release_success_feed_notification(self, deal_id: DealId) -> None: ...
    async def list_completed_without_success_feed(self, limit: int = 20) -> list[Deal]: ...
    async def count_as_buyer(self, buyer_id: TelegramId) -> int: ...
    async def count_as_seller(self, seller_id: TelegramId) -> int: ...
    async def claim_payment(self, deal_id: DealId, payment: PaymentObservation) -> Deal | None: ...
    async def mark_direct_custody(self, deal_id: DealId, delivery_deadline: datetime) -> Deal | None: ...
    async def request_release(self, deal_id: DealId, buyer_id: TelegramId) -> Deal | None: ...
    async def list_release_requested(self, limit: int = 1) -> list[Deal]: ...
    async def list_collecting(self, limit: int = 50) -> list[Deal]: ...
    async def mark_delivered(self, deal_id: DealId, seller_id: TelegramId, deadline: datetime) -> Deal | None: ...
    async def list_delivery_expired(self, limit: int = 50) -> list[Deal]: ...
    async def list_inspection_expired(self, limit: int = 50) -> list[Deal]: ...
    async def request_expired_refund(self, deal_id: DealId) -> Deal | None: ...
    async def request_auto_release(self, deal_id: DealId) -> Deal | None: ...
    async def list_refund_requested(self, limit: int = 1) -> list[Deal]: ...
    async def list_refund_awaiting_wallet(self, limit: int = 50) -> list[Deal]: ...
    async def activate_refund_after_wallet(self, deal_id: DealId) -> Deal | None: ...
    async def list_for_user(self, telegram_id: TelegramId, page: int, page_size: int) -> tuple[list[Deal], int]: ...
    async def list_pending(self, limit: int = 50) -> list[Deal]: ...
    async def request_cancellation(self, deal_id: DealId, actor_id: TelegramId) -> Deal | None: ...
    async def archive_unsuccessful(self, retention_days: int) -> int: ...
    async def cancel_expired_pending(self) -> int: ...
    async def process_deadlines_batch(self, limit: int = 50) -> dict[str, int]: ...
    async def list_channel_transfer_pending(self, limit: int = 20) -> list[Deal]: ...
    async def record_channel_observation(
        self, deal_id: DealId, member_status: str, error: str | None = None
    ) -> None: ...
    async def confirm_channel_owner(self, deal_id: DealId) -> Deal | None: ...
    async def dispute_channel_transfer(self, deal_id: DealId, reason: str) -> Deal | None: ...


class DisputeRepositoryProtocol(Protocol):
    async def open(self, deal_id: DealId, actor_id: TelegramId, description: str) -> DisputeTicket | None: ...


class AdminRepositoryProtocol(Protocol):
    async def list_disputes(self, page: int, page_size: int) -> tuple[list[DisputeTicket], bool]: ...
    async def get_dispute(self, ticket_id: int) -> DisputeTicket | None: ...
    async def resolve_release(self, deal_id: DealId, reason: str) -> Deal | None: ...
    async def resolve_refund(self, deal_id: DealId, reason: str) -> Deal | None: ...
    async def get_settings(self) -> BotSettings: ...
    async def set_maintenance(self, enabled: bool, message: str | None = None) -> BotSettings: ...


class FinancialOperationRepositoryProtocol(Protocol):
    async def plan_collection(
        self, *, deal_id: int, destination: str, comment: str,
        unmatched_payment_id: int | None = None,
    ) -> FinancialOperation | None: ...
    async def plan_payout(self, **values: object) -> list[FinancialOperation]: ...
    async def plan_refund(self, **values: object) -> list[FinancialOperation]: ...
    async def claim_referral_withdrawal(
        self, user_id: int, currency: str, destination: str, comment: str
    ) -> FinancialOperation | None: ...
    async def plan_unmatched_refund(
        self, payment_id: int, destination: str
    ) -> FinancialOperation | None: ...
    async def claim_due(self, flow: FinancialOperationFlow) -> FinancialOperation | None: ...
    async def prepare_attempt(
        self, operation_id: int, prepared: PreparedPayout
    ) -> FinancialOperationAttempt | None: ...
    async def mark_submitted(self, attempt_id: int) -> FinancialOperationAttempt | None: ...
    async def mark_confirmed(
        self, attempt_id: int, transaction_hash: str
    ) -> FinancialOperation | None: ...
    async def schedule_retry(
        self, attempt_id: int, error: str, *, bounced: bool = False, uncertain: bool = False
    ) -> FinancialOperation | None: ...
    async def list_submitted(
        self, flow: FinancialOperationFlow, limit: int = 20
    ) -> list[tuple[FinancialOperation, FinancialOperationAttempt]]: ...
    async def schedule_unprepared_retry(
        self, operation_id: int, error: str
    ) -> FinancialOperation | None: ...
    async def get(self, operation_id: int) -> FinancialOperation | None: ...
    async def list_attempts(
        self, operation_id: int
    ) -> list[FinancialOperationAttempt]: ...
    async def list_for_admin(
        self, page: int, page_size: int
    ) -> tuple[list[FinancialOperation], bool]: ...
    async def reopen(self, operation_id: int, reason: str) -> FinancialOperation | None: ...
    async def mark_manual_review(
        self, operation_id: int, reason: str
    ) -> FinancialOperation | None: ...
    async def force_complete(
        self, operation_id: int, tx_hash: str, reason: str
    ) -> FinancialOperation | None: ...


class DepositRepositoryProtocol(Protocol):
    async def get_cursor(self, scanner: str) -> DepositCursor | None: ...
    async def save_cursor(
        self, scanner: str, account_address: str, last_lt: int, last_hash: str
    ) -> DepositCursor: ...
    async def add_observed(self, values: dict[str, object]) -> ObservedDeposit | None: ...
    async def mark_matched(self, deposit_id: int, deal_id: int) -> None: ...
    async def mark_processed(self, deposit_id: int) -> None: ...
    async def mark_desk_checked(self, deposit_id: int) -> None: ...
    async def add_unmatched(
        self, deposit: ObservedDeposit, reason: str
    ) -> UnmatchedPayment | None: ...
    async def list_unmatched(
        self, page: int, page_size: int
    ) -> tuple[list[UnmatchedPayment], bool]: ...
    async def get_unmatched(self, payment_id: int) -> UnmatchedPayment | None: ...


class ReferralRepositoryProtocol(Protocol):
    async def assign_referrer(self, referrer_id: TelegramId, referred_id: TelegramId) -> bool: ...
    async def get_stats(self, referrer_id: TelegramId) -> ReferralStats: ...
    async def get_profiles(self, user_ids: set[TelegramId]) -> dict[TelegramId, ReferralProfile]: ...
    async def list_enabled_communities(self) -> list[ReferralCommunity]: ...
    async def sync_community_membership(
        self, chat_id: int, telegram_id: TelegramId, telegram_status: str, active: bool
    ) -> bool: ...
    async def add_reward(
        self,
        deal_id: DealId,
        referrer_id: TelegramId,
        referred_id: TelegramId,
        currency: Currency,
        amount: Decimal,
    ) -> bool: ...
    async def claim_withdrawal(
        self, user_id: TelegramId, currency: Currency, destination: str, comment: str
    ) -> ReferralWithdrawal | None: ...
    async def save_prepared_withdrawal(
        self, withdrawal_id: int, external_message_hash: str, signed_boc: str, valid_until: datetime
    ) -> ReferralWithdrawal: ...
    async def mark_withdrawal_submitted(self, withdrawal_id: int) -> ReferralWithdrawal: ...
    async def mark_withdrawal_confirmed(self, withdrawal_id: int) -> ReferralWithdrawal | None: ...
    async def mark_withdrawal_failed(
        self, withdrawal_id: int, error: str, bounced: bool = False
    ) -> ReferralWithdrawal | None: ...
    async def list_open_withdrawals(self) -> list[ReferralWithdrawal]: ...
    async def get_withdrawal(self, withdrawal_id: int) -> ReferralWithdrawal | None: ...


class TonGatewayProtocol(Protocol):
    @property
    def is_connected(self) -> bool: ...
    async def start(self) -> None: ...
    async def close(self) -> None: ...
    def normalize_address(self, raw_address: str) -> str: ...
    @property
    def guarant_address(self) -> str: ...
    async def get_deal_address(self, deal: Deal) -> str: ...
    async def find_incoming_payment(self, deal: Deal) -> PaymentObservation | None: ...
    async def scan_ton_deposits(
        self, deal: Deal, last_lt: int | None, last_hash: str | None
    ) -> DepositScanBatch: ...
    async def prepare_batch_payout(self, deal: Deal, messages: Sequence[PayoutMessage]) -> PreparedPayout: ...
    async def prepare_collection(self, deal: Deal, comment: str) -> PreparedPayout: ...
    async def prepare_guarant_payout(self, messages: Sequence[PayoutMessage]) -> PreparedPayout: ...
    async def broadcast(self, signed_boc: str) -> None: ...
    async def get_collection_trace_status(self, attempt: CollectionAttempt) -> TraceStatus: ...
    async def get_guarant_balance_atomic(self) -> int: ...
    async def get_guarant_asset_balance_atomic(self, currency: Currency) -> int: ...
    async def scan_usdt_deposits(
        self, last_lt: int | None, last_hash: str | None
    ) -> DepositScanBatch: ...
    async def scan_guarant_ton_deposits(
        self, last_lt: int | None, last_hash: str | None
    ) -> DepositScanBatch: ...
    async def get_financial_operation_trace_status(
        self, operation: FinancialOperation, attempt: FinancialOperationAttempt
    ) -> TraceResult: ...


class NotificationGatewayProtocol(Protocol):
    async def buyer_joined(self, deal: Deal, buyer: User, seller: User, buyer_deals: int) -> None: ...
    async def payment_received(self, deal: Deal, buyer: User | None, seller: User | None) -> None: ...
    async def payout_confirmed(self, deal: Deal, buyer: User | None, seller: User | None) -> None: ...
    async def completed_deal_feed(self, deal: Deal) -> bool: ...
    async def refund_confirmed(self, deal: Deal, buyer: User | None, seller: User | None) -> None: ...
    async def delivery_marked(self, deal: Deal, buyer: User | None, seller: User | None) -> None: ...
    async def dispute_opened(self, deal: Deal, buyer: User | None, seller: User | None) -> None: ...
    async def cancelled_by_seller(self, deal: Deal, buyer: User) -> None: ...
