from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from decimal import Decimal
from typing import Literal, Protocol, TypeAlias, TypedDict, Unpack

from app.core.enums import Currency, DealStatus, Language, TraceStatus
from app.models.dto import CreateDealCommand, PaymentObservation, ReferralStats
from app.models.entities import BotSettings, CollectionAttempt, Deal, DisputeTicket, PayoutAttempt, ReferralWithdrawal, RefundAttempt, User
from app.ton.models import PayoutMessage, PreparedPayout

TelegramId: TypeAlias = int
DealId: TypeAlias = int
AtomicAmount: TypeAlias = int
HealthStatus: TypeAlias = Literal["ok", "starting"]


class ReadinessPayload(TypedDict):
    status: HealthStatus
    checks: dict[str, bool]


class UserChanges(TypedDict, total=False):
    username: str | None
    wallet_address: str | None
    language: Language
    referrer_id: int | None


class UserRepositoryProtocol(Protocol):
    async def ensure_user(
        self,
        telegram_id: TelegramId,
        username: str | None,
        default_language: Language,
    ) -> User: ...

    async def get(self, telegram_id: TelegramId) -> User | None: ...

    async def update(self, telegram_id: TelegramId, **changes: Unpack[UserChanges]) -> User: ...
    async def list_ids(self, offset: int, limit: int) -> list[int]: ...


class DealRepositoryProtocol(Protocol):
    async def create(self, command: CreateDealCommand) -> Deal: ...
    async def activate(self, deal_id: DealId, wallet_address: str) -> Deal: ...
    async def mark_creation_failed(self, deal_id: DealId, reason: str) -> Deal: ...
    async def transition(self, deal_id: DealId, expected: DealStatus, **changes: object) -> Deal: ...
    async def get(self, deal_id: DealId) -> Deal | None: ...
    async def get_by_public_id(self, public_id: str) -> Deal | None: ...
    async def join(self, public_id: str, buyer_id: TelegramId) -> Deal | None: ...
    async def claim_payment(self, deal_id: DealId, payment: PaymentObservation) -> Deal | None: ...
    async def mark_direct_custody(self, deal_id: DealId, delivery_deadline: datetime) -> Deal | None: ...
    async def request_release(self, deal_id: DealId, buyer_id: TelegramId) -> Deal | None: ...
    async def list_release_requested(self, limit: int = 1) -> list[Deal]: ...
    async def list_collecting(self) -> list[Deal]: ...
    async def mark_delivered(self, deal_id: DealId, seller_id: TelegramId, deadline: datetime) -> Deal | None: ...
    async def list_delivery_expired(self) -> list[Deal]: ...
    async def list_inspection_expired(self) -> list[Deal]: ...
    async def request_expired_refund(self, deal_id: DealId) -> Deal | None: ...
    async def request_auto_release(self, deal_id: DealId) -> Deal | None: ...
    async def list_refund_requested(self, limit: int = 1) -> list[Deal]: ...
    async def list_refund_awaiting_wallet(self) -> list[Deal]: ...
    async def activate_refund_after_wallet(self, deal_id: DealId) -> Deal | None: ...
    async def list_for_user(self, telegram_id: TelegramId, page: int, page_size: int) -> tuple[list[Deal], bool]: ...
    async def list_pending(self) -> list[Deal]: ...
    async def expire_unpaid(self, deal_id: DealId) -> Deal: ...
    async def purge_unsuccessful(self, retention_days: int) -> int: ...


class PayoutRepositoryProtocol(Protocol):
    async def claim(
        self,
        deal: Deal,
        destination: str,
        amount_atomic: int,
        comment: str,
        reward_destination: str | None,
        reward_nominal_amount_atomic: int | None,
        reward_comment: str | None,
    ) -> PayoutAttempt | None: ...
    async def save_prepared(
        self,
        attempt_id: int,
        external_message_hash: str,
        signed_boc: str,
        valid_until: datetime,
    ) -> PayoutAttempt: ...
    async def mark_submitted(self, attempt_id: int) -> PayoutAttempt: ...
    async def mark_confirmed(self, attempt_id: int) -> Deal | None: ...
    async def mark_bounced(self, attempt_id: int, error: str) -> Deal: ...
    async def mark_failed(self, attempt_id: int, error: str) -> Deal: ...
    async def list_open(self) -> list[PayoutAttempt]: ...


class CollectionRepositoryProtocol(Protocol):
    async def claim(self, deal: Deal, destination: str, comment: str) -> CollectionAttempt | None: ...
    async def save_prepared(
        self,
        attempt_id: int,
        external_message_hash: str,
        signed_boc: str,
        valid_until: datetime,
    ) -> CollectionAttempt: ...
    async def mark_submitted(self, attempt_id: int) -> CollectionAttempt: ...
    async def mark_confirmed(self, attempt_id: int) -> Deal | None: ...
    async def mark_bounced(self, attempt_id: int, error: str) -> Deal: ...
    async def mark_failed(self, attempt_id: int, error: str) -> Deal: ...
    async def list_open(self) -> list[CollectionAttempt]: ...


class RefundRepositoryProtocol(Protocol):
    async def claim(
        self, deal: Deal, destination: str, amount_atomic: int, comment: str, reason: str,
        reward_destination: str, reward_nominal_amount_atomic: int, reward_comment: str,
    ) -> RefundAttempt | None: ...
    async def save_prepared(
        self, attempt_id: int, external_message_hash: str, signed_boc: str, valid_until: datetime
    ) -> RefundAttempt: ...
    async def mark_submitted(self, attempt_id: int) -> RefundAttempt: ...
    async def mark_confirmed(self, attempt_id: int) -> Deal | None: ...
    async def mark_bounced(self, attempt_id: int, error: str) -> Deal: ...
    async def mark_failed(self, attempt_id: int, error: str) -> Deal: ...
    async def list_open(self) -> list[RefundAttempt]: ...


class DisputeRepositoryProtocol(Protocol):
    async def open(self, deal_id: DealId, actor_id: TelegramId, description: str) -> DisputeTicket | None: ...


class AdminRepositoryProtocol(Protocol):
    async def list_disputes(self, page: int, page_size: int) -> tuple[list[DisputeTicket], bool]: ...
    async def get_dispute(self, ticket_id: int) -> DisputeTicket | None: ...
    async def resolve_release(self, deal_id: DealId, reason: str) -> Deal | None: ...
    async def resolve_refund(self, deal_id: DealId, reason: str) -> Deal | None: ...
    async def get_settings(self) -> BotSettings: ...
    async def set_maintenance(self, enabled: bool, message: str | None = None) -> BotSettings: ...


class ReferralRepositoryProtocol(Protocol):
    async def assign_referrer(self, referrer_id: TelegramId, referred_id: TelegramId) -> bool: ...
    async def get_stats(self, referrer_id: TelegramId) -> ReferralStats: ...
    async def add_reward(
        self,
        deal_id: DealId,
        referrer_id: TelegramId,
        referred_id: TelegramId,
        currency: Currency,
        amount: Decimal,
    ) -> bool: ...
    async def claim_withdrawal(
        self, user_id: TelegramId, currency: Currency, destination: str, comment: str
    ) -> ReferralWithdrawal | None: ...
    async def save_prepared_withdrawal(
        self, withdrawal_id: int, external_message_hash: str, signed_boc: str, valid_until: datetime
    ) -> ReferralWithdrawal: ...
    async def mark_withdrawal_submitted(self, withdrawal_id: int) -> ReferralWithdrawal: ...
    async def mark_withdrawal_confirmed(self, withdrawal_id: int) -> ReferralWithdrawal | None: ...
    async def mark_withdrawal_failed(
        self, withdrawal_id: int, error: str, bounced: bool = False
    ) -> ReferralWithdrawal | None: ...
    async def list_open_withdrawals(self) -> list[ReferralWithdrawal]: ...


class TonGatewayProtocol(Protocol):
    @property
    def is_connected(self) -> bool: ...
    async def start(self) -> None: ...
    async def close(self) -> None: ...
    def normalize_address(self, raw_address: str) -> str: ...
    @property
    def guarant_address(self) -> str: ...
    async def get_deal_address(self, deal: Deal) -> str: ...
    async def find_incoming_payment(self, deal: Deal) -> PaymentObservation | None: ...
    async def prepare_batch_payout(self, deal: Deal, messages: Sequence[PayoutMessage]) -> PreparedPayout: ...
    async def prepare_collection(self, deal: Deal, comment: str) -> PreparedPayout: ...
    async def prepare_guarant_payout(self, messages: Sequence[PayoutMessage]) -> PreparedPayout: ...
    async def broadcast(self, signed_boc: str) -> None: ...
    async def get_payout_trace_status(self, attempt: PayoutAttempt) -> TraceStatus: ...
    async def get_collection_trace_status(self, attempt: CollectionAttempt) -> TraceStatus: ...
    async def get_refund_trace_status(self, attempt: RefundAttempt) -> TraceStatus: ...
    async def get_referral_withdrawal_trace_status(
        self, withdrawal: ReferralWithdrawal
    ) -> TraceStatus: ...
    async def get_guarant_balance_atomic(self) -> int: ...
    async def get_guarant_asset_balance_atomic(self, currency: Currency) -> int: ...


class NotificationGatewayProtocol(Protocol):
    async def payment_received(self, deal: Deal, buyer: User | None, seller: User | None) -> None: ...
    async def payout_confirmed(self, deal: Deal, buyer: User | None, seller: User | None) -> None: ...
    async def refund_confirmed(self, deal: Deal, buyer: User | None, seller: User | None) -> None: ...
    async def delivery_marked(self, deal: Deal, buyer: User | None, seller: User | None) -> None: ...
    async def dispute_opened(self, deal: Deal, buyer: User | None, seller: User | None) -> None: ...
